### ISSUE TITLE
Incorrect comparison of Debian versions

### ISSUE THREAD

**Issue by Lastique** [repology/libversion#5]
The algorithm is described here:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

According to it, `1.2~3` is not the same as `1.2.3`, as the title page suggests.

FYI: Fedora versioning guidelines are here: https://fedoraproject.org/wiki/Packaging:Versioning. I did not analyze the algorithm to see if it conforms to these.

**Comment by AMDmi3** [comment]
libversion can't rely solely on Debian policy because it's purpose is to compare generic version strings where a tilde may or may not mean a separator. A tilde may not be processed as a part of a non-digit version component as Debian does, precisely because it's Debian-specific and if we do, we won't be able to compare e.g. `1~beta1` from Debian with e.g `1.beta1` from other distro.

However, the way libversion works still handles tilde correctly in most cases, as e.g. `1~beta1`, `1.beta1` and `1beta1` are all treated equal and lesser-than `1`.

The problem arises with cases like `1~1` though, which libversion would treat as `1.1`, while it's intended to be actually something lower than `1`. Probably the library could treat tilde followed by a number in a special way, as something like `1.<empty string>1` which will compare correctly. Some research is needed though to know if that's compatible with the way other repositories use tilda.

As a side note, there is another problem with tilda, which is related to repology rather than libversion. When parsing Debian repository family (Ubuntu, GetDeb etc.) we just cut away everything after tilda (the idea was it's something like debian_version, which is not true), which leads to some prerelease versions erroneously shown up as releases (see repology/repology#216).

**Comment by Lastique** [comment]
The problem is not just about ~ - if you compare multiple Debian-based distros (or maybe even package repos, like deb-multimedia for example), you should take into account all parts of the Debian version according to the Debian policy. For instance, you should probably take into account epoch and debian_version as well.

Regarding ~, relying on keywords like "beta", which is what libversion does, is unreliable. This will break with snapshot versions like 1.2.3~20170115.git123abcd, which should be less than 1.2.3~2017011**6**.git456ef01 or 1.2.3. Other characters, like +, for instance, are also used to order versions relative to software releases. So, 1.2.3+1.git123abcd (i.e. 1 commit after 1.2.3) should be greater than 1.2.3.

I'm probably missing some specifics of repology, but the front page gives the impression that libversion is supposed to be a general purpose library. As such it should work correctly in general.

**Comment by AMDmi3** [comment]
> you should take into account all parts of the Debian version according to the Debian policy. For instance, you should probably take into account epoch and debian_version as well.

No, because libversion is generic. Repology extracts upstream versions and uses libversion to compare these, so all distro-specific prefixes, suffixes, epoch and revisions are and should be ignored. They do not have any sence outside their distros anyway. Likewise, the tilde should not generally have special meaning if other distros don't use it the same way.

> Regarding ~, relying on keywords like "beta", which is what libversion does, is unreliable.

The only keyword libversion currenly relies on is `patch` (`1patch1 > 1` as opposed to `1beta1 < 1`), all other non-numerics are treated as pre-release by default and that works.

> This will break with snapshot versions like 1.2.3~20170115.git123abcd, which should be less than 1.2.3~20170116.git456ef01 or 1.2.3.

Yes, and that can be solved as described above, as long as it's compatible with other distros.

Though actually, Debian using such schema is terminally broken, because it refers to non-existing release `1.2.3`, so it may be better idea to just ignore all versions containing tilde followed by a number. Be it `1.2.2+20170116`, it would be handled correctly, but as any snapshot it's also candidate to be ignored.

> Other characters, like +, for instance, are also used to order versions relative to software releases. So, 1.2.3+1.git123abcd (i.e. 1 commit after 1.2.3) should be greater than 1.2.3.

This already works.

> As such it should work correctly in general.

It does.

**Comment by Lastique** [comment]
> No, because libversion is generic.

It's not, according to your following comments. I can see now that the library is tailored specifically for repology needs and can't be used e.g. to tell me if a newer version of a package exists in deb-multimedia or debian-security compared to the main debian repo - exactly because it ignores distro-specific parts of the version.

>> This will break with snapshot versions
> Yes, and that can be solved as described above

I don't think I see how.

Anyway, since the library is targeted for repology, this issue can probably be closed as not applicable. I only wish you made it more clear on the front page.

Thank you for your comments.

**Comment by AMDmi3** [comment]
> It's not, according to your following comments. I can see now that the library is tailored specifically for repology needs and 

It is. "Tailoring for repology" is the same as making it most generic, as repology needs to compare versions among 80+ repositories and to do it well.

> can't be used e.g. to tell me if a newer version of a package exists in deb-multimedia or debian-security compared to the main debian repo - exactly because it ignores distro-specific parts of the version.

Because you need Debian-specific and not generic version comparison.
